version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node-utils"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 20
